#!/usr/bin/env sh

# General space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 10

# yabai -m config focus_follows_mouse autofocus

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off