tap "candid82/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "schniz/tap"
tap "yqrashawn/goku"
# Cross-platform make
brew "cmake"
# Command-line tool for DigitalOcean
brew "doctl"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern replacement for 'ls'
brew "exa"
# GNU database manager
brew "gdbm"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Command-line option parsing utility
brew "gnu-getopt"
# AVH edition of git-flow
brew "git-flow-avh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Library for command-line editing
brew "readline"
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Add GitHub support to git on the command-line
brew "hub"
# Configurable static site generator
brew "hugo"
# Version of the SSL/TLS protocol forked from OpenSSL
brew "libressl"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Flexible tool for responding to filesystem changes
brew "modd"
# Fast, highly customisable system info script
brew "neofetch"
# Port scanning utility for large networks
brew "nmap", link: false
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# Generate ASCII art with terminal, shell, and OS info
brew "screenfetch"
# Command-line packet analyzer
brew "tcpdump"
# Programatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Execute commands when watched files change
brew "watchexec"
# Internet file retriever
brew "wget"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# karabiner configurator
brew "yqrashawn/goku/goku"
cask "alfred"
cask "android-platform-tools"
cask "backblaze"
cask "brave-browser"
cask "contexts"
cask "dash"
cask "dotnet-sdk"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "gswitch"
cask "hazel"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "moonlight"
cask "spotify"
cask "steam"
cask "tower"
cask "transmission"
cask "tunnelbear"
cask "visual-studio-code"
cask "webtorrent"
