tap "ajeetdsouza/zoxide"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "schniz/tap"
# Cross-platform make
brew "cmake"
# Command-line tool for DigitalOcean
brew "doctl"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern replacement for 'ls'
brew "exa"
# GNU database manager
brew "gdbm"
# Command-line option parsing utility
brew "gnu-getopt"
# AVH edition of git-flow
brew "git-flow-avh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Library for command-line editing
brew "readline", link: true
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Small Clojure interpreter and linter
brew "joker"
# Execute commands when watched files change
brew "watchexec"
# karabiner configurator
brew "goku", restart_service: true
# Add GitHub support to git on the command-line
brew "hub"
# Configurable static site generator
brew "hugo"
# Version of the SSL/TLS protocol forked from OpenSSL
brew "libressl"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Mac App Store command-line interface
brew "mas"
# Flexible tool for responding to filesystem changes
brew "modd"
# Fast, highly customisable system info script
brew "neofetch"
# Port scanning utility for large networks
brew "nmap"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# Generate ASCII art with terminal, shell, and OS info
brew "screenfetch"
# Programatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Internet file retriever
brew "wget"
# Black box WordPress vulnerability scanner
brew "wpscan"
# Download YouTube videos from the command-line
brew "youtube-dl"
# UNIX shell (command interpreter)
brew "zsh"
# A faster way to navigate your filesystem
brew "ajeetdsouza/zoxide/zoxide"
cask "android-platform-tools"
cask "dotnet"
cask "font-hack-nerd-font"
cask "gswitch"
cask "transmission"
cask "webtorrent"
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "Cascadea", id: 1432182561
mas "Dark Reader for Safari", id: 1438243180
mas "Day One", id: 1055511498
mas "DevCleaner", id: 1388020431
mas "DigiDoc4 Client", id: 1370791134
mas "Drafts", id: 1435957248
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Mast", id: 1437429129
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Pixave", id: 924891282
mas "Pixelmator Pro", id: 1289583905
mas "Save to Pocket", id: 1477385213
mas "Select Like A Boss For Safari", id: 1437310115
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "Streaks", id: 1493327990
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "Tweetbot", id: 1384080005
mas "Vimari", id: 1480933944
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
