tap "ajeetdsouza/zoxide"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "schniz/tap"
# Cross-platform make
brew "cmake"
# Command-line tool for DigitalOcean
brew "doctl"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern replacement for 'ls'
brew "exa"
# GNU database manager
brew "gdbm"
# Command-line option parsing utility
brew "gnu-getopt"
# AVH edition of git-flow
brew "git-flow-avh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Library for command-line editing
brew "readline", link: true
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Small Clojure interpreter and linter
brew "joker"
# Execute commands when watched files change
brew "watchexec"
# karabiner configurator
brew "goku", restart_service: true
# Add GitHub support to git on the command-line
brew "hub"
# Configurable static site generator
brew "hugo"
# Version of the SSL/TLS protocol forked from OpenSSL
brew "libressl"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Flexible tool for responding to filesystem changes
brew "modd"
# Fast, highly customisable system info script
brew "neofetch"
# Port scanning utility for large networks
brew "nmap"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# Generate ASCII art with terminal, shell, and OS info
brew "screenfetch"
# Command-line packet analyzer
brew "tcpdump"
# Programatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Black box WordPress vulnerability scanner
brew "wpscan"
# Download YouTube videos from the command-line
brew "youtube-dl"
# UNIX shell (command interpreter)
brew "zsh"
# A faster way to navigate your filesystem
brew "ajeetdsouza/zoxide/zoxide"
cask "android-platform-tools"
cask "dotnet-sdk"
cask "font-hack-nerd-font"
cask "gswitch"
cask "termius"
cask "transmission"
cask "webtorrent"
